kind: pipeline
name: main

steps:
- name: clippy
  image: rust:latest
  commands:
   - cargo clippy --message-format=json &> clippy.report

- name: sonarqube
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host: 
      from_secret: SONAR_HOST
    sonar_token: 
      from_secret: SONAR_TOKEN